steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: deploy
    entrypoint: bash
    args:
      - '-c'
      - |
        if [[ "$BRANCH_NAME" == "master" ]]; then
          docker build -t us.gcr.io/$PROJECT_ID/firestore-emulator .
          docker push us.gcr.io/$PROJECT_ID/firestore-emulator
        fi
