name: Continuous Deployment

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Publish Docker Image to GPR
        id: publish
        uses: elgohr/Publish-Docker-Github-Action@v1.11
        with:
          name: 'ridedott/firestore-emulator'
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
