name: Continuous Deployment

on:
  pull_request:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Build
        run: |
          VERSION=`cat ./VERSION`
          docker build \
            --build-arg CLOUD_FIRESTORE_EMULATOR_VERSION=$VERSION \
            --tag docker.pkg.github.com/ridedott/firestore-emulator-docker/firestore-emulator:latest \
            --tag docker.pkg.github.com/ridedott/firestore-emulator-docker/firestore-emulator:$VERSION \
            --tag registry.hub.docker.com/ridedott/firestore-emulator:latest \
            --tag registry.hub.docker.com/ridedott/firestore-emulator:$VERSION \
            .
      - name: Release
        env:
          GITHUB_REGISTRY_USERNAME: ${{ secrets.GITHUB_REGISTRY_USERNAME }}
          GITHUB_REGISTRY_PASSWORD: ${{ secrets.GITHUB_REGISTRY_PASSWORD }}
          DOCKER_HUB_REGISTRY_USERNAME:
            ${{ secrets.DOCKER_HUB_REGISTRY_USERNAME }}
          DOCKER_HUB_REGISTRY_PASSWORD:
            ${{ secrets.DOCKER_HUB_REGISTRY_PASSWORD }}
        run: |
          VERSION=`cat ./VERSION`
          # GitHub Package Registry
          echo $GITHUB_REGISTRY_PASSWORD | docker login docker.pkg.github.com --username $GITHUB_REGISTRY_USERNAME --password-stdin
          docker push \
            docker.pkg.github.com/ridedott/firestore-emulator-docker/firestore-emulator:latest
          docker push \
            docker.pkg.github.com/ridedott/firestore-emulator-docker/firestore-emulator:$VERSION
          # Docker Hub
          echo $DOCKER_HUB_REGISTRY_PASSWORD | docker login registry.hub.docker.com --username $DOCKER_HUB_REGISTRY_USERNAME --password-stdin
          docker push \
            registry.hub.docker.com/ridedott/firestore-emulator:latest
          VERSION=`cat ./VERSION`
          docker push \
            registry.hub.docker.com/ridedott/firestore-emulator:$VERSION
