name: Continuous Delivery

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - env:
          DOCKER_BUILDKIT: 1
          GITHUB_REGISTRY_USERNAME: ${{ github.actor }}
          GITHUB_REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        name: Build and release
        run: |
          # GitHub Packages Registry
          echo $GITHUB_REGISTRY_PASSWORD | docker login ghcr.io --username $GITHUB_REGISTRY_USERNAME --password-stdin

          VERSION=`cat ./VERSION`
          docker buildx build \
            --build-arg CLOUD_FIRESTORE_EMULATOR_VERSION=$VERSION \
            --output=type=registry \
            --platform linux/amd64,linux/arm64 \
            --tag ghcr.io/ridedott/firestore-emulator:latest \
            --tag ghcr.io/ridedott/firestore-emulator:$VERSION \
            .
