name: Continuous Integration

on:
  pull_request:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Build
        run: docker build -t docker.pkg.github.com/ridedott/firestore-emulator-docker/firestore-emulator:dev .
