name: Continuous Deployment

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Build
        run: |
          VERSION=`cat ./VERSION`
          docker build \
            --build-arg CLOUD_FIRESTORE_EMULATOR_VERSION=$VERSION
            -t docker.pkg.github.com/ridedott/firestore-emulator-docker/firestore-emulator:latest \
            -t docker.pkg.github.com/ridedott/firestore-emulator-docker/firestore-emulator:$VERSION \
            .
      - name: Release
        env:
          GITHUB_REGISTRY_USERNAME: ${{ secrets.GITHUB_REGISTRY_USERNAME }}
          GITHUB_REGISTRY_PASSWORD: ${{ secrets.GITHUB_REGISTRY_PASSWORD }}
        run: |
          echo $GITHUB_REGISTRY_PASSWORD | docker login docker.pkg.github.com --username $GITHUB_REGISTRY_USERNAME --password-stdin
          docker push \
            docker.pkg.github.com/ridedott/firestore-emulator-docker/firestore-emulator:latest
          VERSION=`cat ./VERSION`
          docker push \
            docker.pkg.github.com/ridedott/firestore-emulator-docker/firestore-emulator:$VERSION
