name: Continuous Integration

on:
  pull_request:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Build
        run: docker build -t docker.pkg.github.com/ridedott/firestore-emulator-docker/firestore-emulator:latest .
      - name: Release
        env:
          GITHUB_REGISTRY_USERNAME: ${{ secrets.GITHUB_REGISTRY_USERNAME }}
          GITHUB_REGISTRY_PASSWORD: ${{ secrets.GITHUB_REGISTRY_PASSWORD }}
        run: |
          echo $GITHUB_TOKEN | docker login docker.pkg.github.com --username ridedott --password-stdin
          docker push docker.pkg.github.com/ridedott/firestore-emulator-docker/firestore-emulator:latest
