name: Continuous Delivery

on:
  push:
    branches:
      - master
      - merlinnot/buildx

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - env:
          DOCKER_BUILDKIT: 1
        name: Build
        run: |
          VERSION=`cat ./VERSION`
          docker buildx build \
            --build-arg CLOUD_FIRESTORE_EMULATOR_VERSION=$VERSION \
            --output=type=docker \
            --platform linux/amd64,linux/arm64 \
            --tag docker.pkg.github.com/ridedott/firestore-emulator-docker/firestore-emulator:latest \
            --tag docker.pkg.github.com/ridedott/firestore-emulator-docker/firestore-emulator:$VERSION \
            --tag registry.hub.docker.com/ridedott/firestore-emulator:latest \
            --tag registry.hub.docker.com/ridedott/firestore-emulator:$VERSION \
            .
      - env:
          GITHUB_REGISTRY_USERNAME: ${{ github.actor }}
          GITHUB_REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_HUB_REGISTRY_USERNAME: ${{ secrets.DOCKER_HUB_REGISTRY_USERNAME }}
          DOCKER_HUB_REGISTRY_PASSWORD: ${{ secrets.DOCKER_HUB_REGISTRY_PASSWORD }}
        name: Release
        run: |
          VERSION=`cat ./VERSION`
          # GitHub Package Registry
          echo $GITHUB_REGISTRY_PASSWORD | docker login docker.pkg.github.com --username $GITHUB_REGISTRY_USERNAME --password-stdin
          docker push \
            docker.pkg.github.com/ridedott/firestore-emulator-docker/firestore-emulator:latest
          docker push \
            docker.pkg.github.com/ridedott/firestore-emulator-docker/firestore-emulator:$VERSION
          # Docker Hub
          echo $DOCKER_HUB_REGISTRY_PASSWORD | docker login registry.hub.docker.com --username $DOCKER_HUB_REGISTRY_USERNAME --password-stdin
          docker push \
            registry.hub.docker.com/ridedott/firestore-emulator:latest
          docker push \
            registry.hub.docker.com/ridedott/firestore-emulator:$VERSION
