name: Continuous Integration

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
        with:
          persist-credentials: false
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - env:
          DOCKER_BUILDKIT: 1
        name: Build
        run: |
          VERSION=`cat ./VERSION`
          docker buildx build \
            --build-arg CLOUD_FIRESTORE_EMULATOR_VERSION=$VERSION \
            --platform linux/amd64,linux/arm64 \
            .
