name: Continuous Deployment

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Publish Docker Image to GPR
        id: publish
        uses: machine-learning-apps/gpr-docker-publish@v1.3
        with:
          USERNAME: ${{ secrets.GPR_USERNAME }}
          PASSWORD: ${{ secrets.GPR_PASSWORD }}
          IMAGE_NAME: 'firestore-emulator'
          DOCKERFILE_PATH: './'
          BUILD_CONTEXT: './'
