name: Continuous Integration

on: push

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - env:
          CI: true
        run: npm ci --unsafe-perm
      - run: npm run format
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - env:
          CI: true
        run: npm ci --unsafe-perm
      - run: npm run lint
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - env:
          CI: true
        run: npm ci --unsafe-perm
      - run: npm run spellcheck
  types:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - env:
          CI: true
        run: npm ci --unsafe-perm
      - run: npm run types
