name: Continuous Deployment

on:
  push:
    branches:
      - master

jobs:
  production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: Remove postinstall hook
        run: |
          sed -i.bak -e '/postinstall/d' package.json
          rm -rf package.json.bak
      - run: npm ci --unsafe-perm
      - run: npm run build
      - env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: npm run deploy:production
